app = 'backend'
primary_region = 'hkg'

[build]

[env]
PORT = '8080'

[mounts]
source = "db"                  # ⚠️ Replace 'data_volume' with a name for your volume
destination = "/db"            # Mount point inside the container (e.g., where your app stores data)
auto_extend_size_threshold = 0

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 1
processes = ['server']

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
